name: Flask App CI/CD with SAST and DAST

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Tests
      - name: Run Tests
        run: python -m unittest discover

      # Step 5: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: PythonTestApp
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep with OWASP Top 10 Rules
        run: semgrep --config "p/owasp-top-ten" --config "p/secrets" --metrics=off

  zap:
    name: OWASP ZAP Full scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Pull OWASP ZAP Docker image
        run: docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Run OWASP ZAP Full Scan
        run: |
          docker run --user root -v $(pwd):/tmp/ ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
            -t https://pythontestapp-cre6agcpddghczer.australiaeast-01.azurewebsites.net \
            -r /tmp/zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
  
  # dast:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     # Step 1: Install OWASP ZAP
  #     - name: Set up OWASP ZAP
  #       uses: zaproxy/action-full-scan@v0.4.0
  #       with:
  #         target: https://pythontestapp-cre6agcpddghczer.australiaeast-01.azurewebsites.net
  #         rules-file: owasp-zap-rules.json
